import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Notification from "@/app/components/Notification";
import LayoutPage from "./components/LayoutPage";
import { Providers } from "./providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "joo doo",
  description: "Generated by Eric Strohmaier.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      id="blogstack-html"
      className="main-font"
      data-color-mode="light"
    >
     
      <body className="font-main">
        <>
          <Providers>
            <LayoutPage>
              {children}
            </LayoutPage>
            <Notification />
          </Providers>
        </>
      </body>
    </html>
  );
}
