import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Notification from "@/app/components/Notification";
import LayoutPage from "./components/LayoutPage";
import { Providers } from "./providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "let's be aware",
  description: "Generated by Eric Strohmaier.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="font-main">
        <>
          <Providers>
            <LayoutPage>
              <div className="m-6 mt-12">{children}</div>
            </LayoutPage>
            <Notification />
          </Providers>
        </>
      </body>
    </html>
  );
}
